### ISSUE TITLE
dynamodbStreams.describeStream fails (added breaking example)

### ISSUE THREAD

**Issue by mvayngrib** [atlassian/localstack#114]
see: https://github.com/mvayngrib/localstack-test/blob/master/dynamodbStreams.js

this example
1. creates a table (if it doesn't exist)
2. creates a record
3. tries to read the streams

shell output:
```sh
creating table EventsTable
table EventsTable already exists
creating record
created record
Stream: arn:aws:dynamodb:us-east-1:000000000000:table/EventsTable/stream/2017-05-30T17:15:14
{ UnknownError: INTERNAL SERVER ERROR
    at Request.extractError (/Users/tenaciousmv/Code/localstack-test/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/Users/tenaciousmv/Code/localstack-test/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/tenaciousmv/Code/localstack-test/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/tenaciousmv/Code/localstack-test/node_modules/aws-sdk/lib/request.js:678:14)
    at Request.transition (/Users/tenaciousmv/Code/localstack-test/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/tenaciousmv/Code/localstack-test/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/tenaciousmv/Code/localstack-test/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/tenaciousmv/Code/localstack-test/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/tenaciousmv/Code/localstack-test/node_modules/aws-sdk/lib/request.js:680:12)
    at Request.callListeners (/Users/tenaciousmv/Code/localstack-test/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'INTERNAL SERVER ERROR',
  code: 'UnknownError',
  statusCode: 500,
  time: 2017-05-30T17:19:13.797Z,
  requestId: undefined,
  retryable: true }
```

**Comment by mvayngrib** [comment]
oops, forgot to add the log from the container:
```sh
$ docker-compose up
Starting localstack_localstack_1
Attaching to localstack_localstack_1
localstack_1  | /usr/lib/python2.7/site-packages/supervisor/options.py:296: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
localstack_1  |   'Supervisord is running as root and it is searching '
localstack_1  | 2017-05-30 17:27:31,709 CRIT Supervisor running as root (no user in config file)
localstack_1  | 2017-05-30 17:27:31,710 INFO supervisord started with pid 1
localstack_1  | 2017-05-30 17:27:32,717 INFO spawned: 'dashboard' with pid 9
localstack_1  | 2017-05-30 17:27:32,719 INFO spawned: 'infra' with pid 10
localstack_1  | (. .venv/bin/activate; bin/localstack web --port=8080)
localstack_1  | . .venv/bin/activate; PYTHONPATH=. exec localstack/mock/infra.py
localstack_1  | Starting local dev environment. CTRL-C to quit.
localstack_1  |  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
localstack_1  |  * Restarting with stat
localstack_1  | Starting mock S3 (port 4572)...
localstack_1  | Starting mock DynamoDB (port 4569)...
localstack_1  | Starting mock DynamoDB Streams service (port 4570)...
localstack_1  | Starting mock Lambda service (port 4574)...
localstack_1  | Starting mock CloudFormation (port 4581)...
localstack_1  |  * Debugger is active!
localstack_1  |  * Debugger PIN: 141-497-473
localstack_1  | 2017-05-30 17:27:34,183 INFO success: dashboard entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_1  | 2017-05-30 17:27:34,184 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_1  | ERROR:ddb_streams_mock:Exception on / [POST]
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
localstack_1  |     response = self.full_dispatch_request()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
localstack_1  |     rv = self.handle_user_exception(e)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
localstack_1  |     reraise(exc_type, exc_value, tb)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
localstack_1  |     rv = self.dispatch_request()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
localstack_1  |     return self.view_functions[rule.endpoint](**req.view_args)
localstack_1  |   File "/opt/code/localstack/localstack/mock/apis/dynamodbstreams_api.py", line 40, in post_request
localstack_1  |     return jsonify(result)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/json.py", line 237, in jsonify
localstack_1  |     return current_app.response_class(dumps(dict(*args, **kwargs),
localstack_1  | TypeError: 'NoneType' object is not iterable
localstack_1  | ERROR:ddb_streams_mock:Exception on / [POST]
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
localstack_1  |     response = self.full_dispatch_request()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
localstack_1  |     rv = self.handle_user_exception(e)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
localstack_1  |     reraise(exc_type, exc_value, tb)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
localstack_1  |     rv = self.dispatch_request()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
localstack_1  |     return self.view_functions[rule.endpoint](**req.view_args)
localstack_1  |   File "/opt/code/localstack/localstack/mock/apis/dynamodbstreams_api.py", line 40, in post_request
localstack_1  |     return jsonify(result)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/json.py", line 237, in jsonify
localstack_1  |     return current_app.response_class(dumps(dict(*args, **kwargs),
localstack_1  | TypeError: 'NoneType' object is not iterable
localstack_1  | WARNING: Unknown operation "DynamoDBStreams_20120810.DescribeStream"
localstack_1  | WARNING: Unknown operation "DynamoDBStreams_20120810.DescribeStream"
localstack_1  | Ready.
localstack_1  | ERROR:ddb_streams_mock:Exception on / [POST]
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
localstack_1  |     response = self.full_dispatch_request()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
localstack_1  |     rv = self.handle_user_exception(e)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
localstack_1  |     reraise(exc_type, exc_value, tb)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
localstack_1  |     rv = self.dispatch_request()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
localstack_1  |     return self.view_functions[rule.endpoint](**req.view_args)
localstack_1  |   File "/opt/code/localstack/localstack/mock/apis/dynamodbstreams_api.py", line 40, in post_request
localstack_1  |     return jsonify(result)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/json.py", line 237, in jsonify
localstack_1  |     return current_app.response_class(dumps(dict(*args, **kwargs),
localstack_1  | TypeError: 'NoneType' object is not iterable
localstack_1  | ERROR:ddb_streams_mock:Exception on / [POST]
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
localstack_1  |     response = self.full_dispatch_request()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
localstack_1  |     rv = self.handle_user_exception(e)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
localstack_1  |     reraise(exc_type, exc_value, tb)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
localstack_1  |     rv = self.dispatch_request()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
localstack_1  |     return self.view_functions[rule.endpoint](**req.view_args)
localstack_1  |   File "/opt/code/localstack/localstack/mock/apis/dynamodbstreams_api.py", line 40, in post_request
localstack_1  |     return jsonify(result)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/json.py", line 237, in jsonify
localstack_1  |     return current_app.response_class(dumps(dict(*args, **kwargs),
localstack_1  | TypeError: 'NoneType' object is not iterable
```

**Comment by whummer** [comment]
Thanks for providing the test project. This is fixed in commit 18ee88e1d4a0827b843d6698df3d3492919966d7 , new version `0.5.0` of the Docker image is currently being built and pushed: https://bitbucket.org/atlassian/localstack/addon/pipelines/home#!/results/%7B898fa013-99b9-4575-8f3c-a2326bad921d%7D
As usual, please confirm that it works for you. Thanks

**Comment by mvayngrib** [comment]
@whummer thanks. I just pulled and retried my example, but it seems to get stuck on creating a table with streams enabled, and never returns. When I Ctrl+C and retry, it doesn't find the stream in listStream

**Comment by whummer** [comment]
I think I found the issue, seems to be related to the fact that DynamoDB was storing tables per account/region, which then results in a mismatch because your node client is using different credentials than the test credentials baked into LocalStack.

I've pushed another minor change, please try again now. That's what it looks like for me now:
```
$ node dynamodbStreams.js 
creating table EventsTable
created table EventsTable
creating record
created record
Stream: arn:aws:dynamodb:us-east-1:000000000000:table/EventsTable/stream/2017-05-31T11:33:47
StreamDescription: [object Object]
[
  {
    "eventID": "1",
    "eventName": "INSERT",
    "eventVersion": "1.0",
    "eventSource": "aws:dynamodb",
    "awsRegion": "us-east-1",
    "dynamodb": {
      "Keys": {
        "id": {
          "S": "Wed May 31 2017 13:33:47 GMT+0200 (CEST)"
        }
      },
      "NewImage": {
        "id": {
          "S": "Wed May 31 2017 13:33:47 GMT+0200 (CEST)"
        }
      },
      "SequenceNumber": "1",
      "SizeBytes": -1,
      "StreamViewType": "NEW_AND_OLD_IMAGES"
    }
  }
]
```

Latest deployment is running here: https://bitbucket.org/atlassian/localstack/addon/pipelines/home#!/results/%7B387fcc7d-addf-4c0f-b582-a5ea7597f619%7D

Btw, I had to make a minor change in your script to fix a `ReferenceError`:
```
-  console.log(`StreamDecription: ${StreamDecription}`)
+  console.log(`StreamDescription: ${StreamDescription}`)
```

**Comment by mvayngrib** [comment]
@whummer awesome, thanks, will try in a bit!

**Comment by mvayngrib** [comment]
@whummer just tried with the latest image, but it still hangs on creating the table. Maybe your fix didn't make it into the latest image?

```sh
Pulling localstack (atlassianlabs/localstack:latest)...
latest: Pulling from atlassianlabs/localstack
Digest: sha256:27fb1a29f0289dd6589ff6409bb712f5699f7b418409df1815b8734c94f0b9ad
Status: Image is up to date for atlassianlabs/localstack:latest
```

**Comment by whummer** [comment]
The fix did make it into that image, but apparently it was not fixing your particular issue. I observed that there have been some issues with persistence - are you by any chance using the `DATA_DIR` environment variable?

I just pushed another change (image hash sha256:bf4940f3d3578415bcf4b8a5bd538d5bc68f7bc1c34ab5e4a5686b092faa5e2e) which might fix it, otherwise I'm afraid we need to continue debugging this issue in more detail.

* Did you set any of the configuration environment variables (e.g., `DATA_DIR`)? If not, could you give it a try and set `DATA_DIR=/tmp/localstack/data` when running LocalStack and then inspect the content of `/tmp/localstack/data/dynamodb`? It should contain a file `shared-local-instance.db` which persists the DB state.
* Does it work if you spin up LocalStack locally via `make infra` instead of using Docker?
* Does it maybe work if you run `make run-docker` instead of starting via `docker-compose`?
* Also, when you say that it "hangs" - how much time did you give it? (In case of API errors, the boto3 client library that we use in LocalStack has some retry logic built in that uses exponential backoff, hence it might take up to a minute or so until the error surfaces through the API to the client. It should not take more than 2 minutes max., though).
* Did you observe any errors in the log output of the container?
* Can you provide some more details about your environment - OS, Docker version, ...

I'm sorry for the painful dev/debugging loop - I wish there was a better way for you to test a change than always having to download a 500MB Docker image, but currently that's the only reliable way of making sure we're using the exact same version. Unless you manage to set up an environment to reliably reproduce the error. For instance a build on Bamboo/Bitbucket Pipelines/TravisCI, or an AWS instance that I can get access to? That would probably make our lives easier.

**Comment by mvayngrib** [comment]
@whummer thanks for your continued help. The first thing I tried was `make docker-run` instead of `docker-compose up` and it worked! 

Meanwhile, here's my previous setup:

macOS 10.12.5
docker version 17.03.1-ce, build c6d412e
docker-compose version 1.11.2, build dfed245
.env contents (DATA_DIR was commented out):
```
SERVICES=dynamodb,dynamodbstreams,lambda,s3,cloudformation
DEFAULT_REGION=us-east-1
HOSTNAME=localhost
KINESIS_ERROR_PROBABILITY=0
DYNAMODB_ERROR_PROBABILITY=0
LAMBDA_EXECUTOR=local
#DATA_DIR=/tmp/localstack/data
```

I waited 2 minutes for createTable. I think it timed out, judging by compose's log output (it moved on to listStreams i think and timed out there too):

```
$ docker-compose up
Starting localstack_localstack_1
Attaching to localstack_localstack_1
localstack_1  | /usr/lib/python2.7/site-packages/supervisor/options.py:296: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
localstack_1  |   'Supervisord is running as root and it is searching '
localstack_1  | 2017-06-01 04:40:25,627 CRIT Supervisor running as root (no user in config file)
localstack_1  | 2017-06-01 04:40:25,630 INFO supervisord started with pid 1
localstack_1  | 2017-06-01 04:40:26,637 INFO spawned: 'dashboard' with pid 9
localstack_1  | 2017-06-01 04:40:26,640 INFO spawned: 'infra' with pid 10
localstack_1  | (. .venv/bin/activate; bin/localstack web --port=8080)
localstack_1  | . .venv/bin/activate; PYTHONPATH=. exec localstack/mock/infra.py
localstack_1  | Starting local dev environment. CTRL-C to quit.
localstack_1  |  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
localstack_1  |  * Restarting with stat
localstack_1  | Starting mock S3 (port 4572)...
localstack_1  | Starting mock DynamoDB (port 4569)...
localstack_1  | Starting mock DynamoDB Streams service (port 4570)...
localstack_1  | Starting mock Lambda service (port 4574)...
localstack_1  | Starting mock CloudFormation (port 4581)...
localstack_1  |  * Debugger is active!
localstack_1  |  * Debugger PIN: 561-920-977
localstack_1  | 2017-06-01 04:40:28,092 INFO success: dashboard entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_1  | 2017-06-01 04:40:28,092 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_1  | Ready.
localstack_1  | ERROR:localstack.mock.generic_proxy:Error forwarding request: Failed to get active status for stream "__ddb_stream_EventsTable", giving up
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/mock/generic_proxy.py", line 138, in forward
localstack_1  |     data=data, headers=forward_headers, response=response)
localstack_1  |   File "/opt/code/localstack/localstack/mock/proxy/dynamodb_listener.py", line 88, in update_dynamodb
localstack_1  |     view_type=view_type, enabled=enabled)
localstack_1  |   File "/opt/code/localstack/localstack/mock/apis/dynamodbstreams_api.py", line 26, in add_dynamodb_stream
localstack_1  |     aws_stack.create_kinesis_stream(stream_name)
localstack_1  |   File "/opt/code/localstack/localstack/utils/aws/aws_stack.py", line 453, in create_kinesis_stream
localstack_1  |     stream.wait_for()
localstack_1  |   File "/opt/code/localstack/localstack/utils/aws/aws_models.py", line 90, in wait_for
localstack_1  |     raise Exception('Failed to get active status for stream "%s", giving up' % self.stream_name)
localstack_1  | Exception: Failed to get active status for stream "__ddb_stream_EventsTable", giving up
```

with `make docker-run`, createTable took 5-7 seconds

I'll see if maybe I can set up a shared AWS instance. Meanwhile, thanks again for the help and responsiveness!

**Comment by whummer** [comment]
Ah interesting, so it looks like the error occurs when calling the Kinesis API (which is used under the hood for DynamoDB Streams). The persistent data might be corrupted (there was a version update of `kinesalite` recently which we reverted due to incompatibility) - could you try deleting the directory `/tmp/localstack/data/kinesis`, and then trying to run the test again using `docker-compose up`. Thanks

**Comment by mvayngrib** [comment]
@whummer yep, seems like setting the DATA_DIR makes `docker-compose up` work (i didn't have it set previously so there was nothing to clear in /tmp/...

**Comment by whummer** [comment]
I'm glad it works now. I'm closing this issue, please re-open if the problem persists. Thanks
