### ISSUE TITLE
socket hang-up on serverless deploy

### ISSUE THREAD

**Issue by mvayngrib** [atlassian/localstack#120]
I'm trying to use the Serverless framework to deploy to localstack. I have a fork that targets localstack services when IS_LOCAL is set: https://github.com/mvayngrib/serverless/tree/localstack (the tweak is based on one of the issues in this repo)

I'm having trouble deploying the stack:

```sh
Serverless: Packaging service...
targeting LOCALSTACK
Serverless: Creating Stack...
targeting LOCALSTACK
Serverless: Checking Stack create progress...
targeting LOCALSTACK
..
Serverless: Stack create finished...
targeting LOCALSTACK
Serverless: Uploading CloudFormation file to S3...
targeting LOCALSTACK
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (5.33 MB)...
targeting LOCALSTACK
Serverless: Updating Stack...
targeting LOCALSTACK
 
  Serverless Error ---------------------------------------
 
     socket hang up
 
  Stack Trace --------------------------------------------
 
ServerlessError: socket hang up
    at Response.req.send (/Users/tenaciousmv/Code/tradle-serverless/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:175:20)
```

the log from the localstack containers:
```sh
Ready.
ERROR:localstack.mock.generic_proxy:Error forwarding request: Unable to parse response (syntax error: line 1, column 54), invalid XML received:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/mock/generic_proxy.py", line 138, in forward
    data=data, headers=forward_headers, response=response)
  File "/opt/code/localstack/localstack/mock/proxy/cloudformation_listener.py", line 150, in update_cloudformation
    template_deployer.deploy_template(template, req_data.get('StackName')[0])
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 337, in deploy_template
    resource['__details__'] = describe_stack_resources(stack_name, resource_id)[0]
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 152, in describe_stack_resources
    resources = client.describe_stack_resources(StackName=stack_name, LogicalResourceId=logical_resource_id)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 544, in _make_api_call
    operation_model, request_dict)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/endpoint.py", line 168, in _send_request
    request, operation_model, attempts)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/endpoint.py", line 233, in _get_response
    response_dict, operation_model.output_shape)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/parsers.py", line 210, in parse
    parsed = self._do_error_parse(response, shape)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/parsers.py", line 438, in _do_error_parse
    root = self._parse_xml_string_to_dom(xml_contents)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/parsers.py", line 390, in _parse_xml_string_to_dom
    "invalid XML received:\n%s" % (e, xml_string))
ResponseParserError: Unable to parse response (syntax error: line 1, column 54), invalid XML received:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

ERROR:localstack.mock.generic_proxy:Error forwarding request: Unable to parse response (syntax error: line 1, column 54), invalid XML received:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/mock/generic_proxy.py", line 138, in forward
    data=data, headers=forward_headers, response=response)
  File "/opt/code/localstack/localstack/mock/proxy/cloudformation_listener.py", line 150, in update_cloudformation
    template_deployer.deploy_template(template, req_data.get('StackName')[0])
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 337, in deploy_template
    resource['__details__'] = describe_stack_resources(stack_name, resource_id)[0]
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 152, in describe_stack_resources
    resources = client.describe_stack_resources(StackName=stack_name, LogicalResourceId=logical_resource_id)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 544, in _make_api_call
    operation_model, request_dict)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/endpoint.py", line 168, in _send_request
    request, operation_model, attempts)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/endpoint.py", line 233, in _get_response
    response_dict, operation_model.output_shape)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/parsers.py", line 210, in parse
    parsed = self._do_error_parse(response, shape)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/parsers.py", line 438, in _do_error_parse
    root = self._parse_xml_string_to_dom(xml_contents)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/parsers.py", line 390, in _parse_xml_string_to_dom
    "invalid XML received:\n%s" % (e, xml_string))
ResponseParserError: Unable to parse response (syntax error: line 1, column 54), invalid XML received:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

ERROR:localstack.mock.generic_proxy:Error forwarding request: Unable to parse response (syntax error: line 1, column 54), invalid XML received:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/mock/generic_proxy.py", line 138, in forward
    data=data, headers=forward_headers, response=response)
  File "/opt/code/localstack/localstack/mock/proxy/cloudformation_listener.py", line 150, in update_cloudformation
    template_deployer.deploy_template(template, req_data.get('StackName')[0])
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 337, in deploy_template
    resource['__details__'] = describe_stack_resources(stack_name, resource_id)[0]
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 152, in describe_stack_resources
    resources = client.describe_stack_resources(StackName=stack_name, LogicalResourceId=logical_resource_id)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 544, in _make_api_call
    operation_model, request_dict)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/endpoint.py", line 168, in _send_request
    request, operation_model, attempts)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/endpoint.py", line 233, in _get_response
    response_dict, operation_model.output_shape)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/parsers.py", line 210, in parse
    parsed = self._do_error_parse(response, shape)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/parsers.py", line 438, in _do_error_parse
    root = self._parse_xml_string_to_dom(xml_contents)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/parsers.py", line 390, in _parse_xml_string_to_dom
    "invalid XML received:\n%s" % (e, xml_string))
ResponseParserError: Unable to parse response (syntax error: line 1, column 54), invalid XML received:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

ERROR:localstack.mock.generic_proxy:Error forwarding request: Unable to parse response (syntax error: line 1, column 54), invalid XML received:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/mock/generic_proxy.py", line 138, in forward
    data=data, headers=forward_headers, response=response)
  File "/opt/code/localstack/localstack/mock/proxy/cloudformation_listener.py", line 150, in update_cloudformation
    template_deployer.deploy_template(template, req_data.get('StackName')[0])
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 337, in deploy_template
    resource['__details__'] = describe_stack_resources(stack_name, resource_id)[0]
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 152, in describe_stack_resources
    resources = client.describe_stack_resources(StackName=stack_name, LogicalResourceId=logical_resource_id)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 544, in _make_api_call
    operation_model, request_dict)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/endpoint.py", line 168, in _send_request
    request, operation_model, attempts)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/endpoint.py", line 233, in _get_response
    response_dict, operation_model.output_shape)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/parsers.py", line 210, in parse
    parsed = self._do_error_parse(response, shape)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/parsers.py", line 438, in _do_error_parse
    root = self._parse_xml_string_to_dom(xml_contents)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/parsers.py", line 390, in _parse_xml_string_to_dom
    "invalid XML received:\n%s" % (e, xml_string))
ResponseParserError: Unable to parse response (syntax error: line 1, column 54), invalid XML received:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
``` 

@whummer, i gave you access to our repo, where you can see the associated serverless.yml. I'd rather not share the repo publicly yet :)

**Comment by mvayngrib** [comment]
nm, here's a much more basic reproduction: https://github.com/mvayngrib/localstack-serverless

to reproduce:

```sh
npm install
npm run deploy:local
```

**Comment by whummer** [comment]
This should be fixed in commit 4f5ff02cf72d6c092558823dfe178a64ce96382e , please try the latest version.

After starting LocalStack via `docker-compose up`, I get this output when running your test:
```
$ npm run deploy:local

> localstack-serverless@1.0.0 deploy:local /tmp/localstack-serverless1
> IS_LOCAL=1 serverless deploy

Serverless: Packaging service...
targeting LOCALSTACK
Serverless: Creating Stack...
targeting LOCALSTACK
Serverless: Checking Stack create progress...
targeting LOCALSTACK
..
Serverless: Stack create finished...
targeting LOCALSTACK
Serverless: Uploading CloudFormation file to S3...
targeting LOCALSTACK
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (9.94 KB)...
targeting LOCALSTACK
Serverless: Updating Stack...
targeting LOCALSTACK
Serverless: Checking Stack update progress...
targeting LOCALSTACK
..
Serverless: Stack update finished...
targeting LOCALSTACK
Service Information
service: localstack-test
stage: dev
region: us-east-1
api keys:
  None
endpoints:
  None
functions:
  hello: localstack-test-dev-hello
targeting LOCALSTACK
```

Then, invoking the serverless Lambda function works as follows:
```
$ aws --endpoint-url=http://localhost:4567 apigateway get-rest-apis | grep id
            "id": "2A-Z77360454",
$ curl http://localhost:4567/restapis/2A-Z77360454/v1/_user_request_/hello/a
"\u001b[32mSTART RequestId: e2942d2a-1f2c-18cb-a9bc-d51e46880c16 Version: $LATEST\u001b[0m\n\u001b[32mEND RequestId: e2942d2a-1f2c-18cb-a9bc-d51e46880c16\u001b[0m\n\u001b[32mREPORT RequestId: e2942d2a-1f2c-18cb-a9bc-d51e46880c16\tDuration: 5.72 ms\tBilled Duration: 100 ms\tMemory Size: 1536 MB\tMax Memory Used: 29 MB\t\u001b[0m\n{\"statusCode\":200,\"body\":\"{\\\"message\\\":\\\"Go Serverless v1.0! Your function executed successfully!\\\",\\\"input\\\":{\\\"body\\\":null,\\\"headers\\\":{\\\"host\\\":\\\"127.0.0.1:4583\\\",\\\"accept\\\":\\\"*/*\\\",\\\"user-agent\\\":\\\"curl/7.49.1\\\"},\\\"resource\\\":\\\"TODO\\\",\\\"queryStringParameters\\\":{},\\\"httpMethod\\\":\\\"TODO\\\",\\\"stageVariables\\\":{},\\\"path\\\":\\\"/hello/a\\\",\\\"pathParameters\\\":{},\\\"isBase64Encoded\\\":false}}\"}"
```

**Comment by mvayngrib** [comment]
@whummer awesome! Will try in a bit

**Comment by whummer** [comment]
PS: The Docker image has now been built and pushed. New image hash: sha256:91b7dad86f141366bf28d47e7576a5c3a61fd36845cc148d0780462ee078713f

**Comment by mvayngrib** [comment]
@whummer ok, i can confirm that this example works: https://github.com/mvayngrib/localstack-serverless

I'm still getting the same error in the private repo I shared with you, but it's a much more complex setup

**Comment by whummer** [comment]
Thanks for confirming that the example works. I'm closing this off for now, please open a new ticket once you've identified a new specific issue. Thanks
