### ISSUE TITLE
SQS: why do I always get the MD5 of message attributes when sending a message?

### ISSUE THREAD

**Issue by luismontreal** [atlassian/localstack#136]
why do I always get the MD5 of message attributes when sending a message?
example:

aws --profil local sqs send-message --queue-url http://localhost:4576/Development-Luis --message-body  'my mesage' --endpoint-url=http://localhost:4576

Response:
{
    "MD5OfMessageBody": "f543352d5773ba2530f769bc8edcf94a", 
    "MD5OfMessageAttributes": "d41d8cd98f00b204e9800998ecf8427e", 
    "MessageId": "2070ad93-d1cc-6014-1027-751cf83c3de7"
}

When making the same call to amazon I only get MD5 of the message body and the message Id

The problem that I'm facing now is that starting from the AWS PHP sdk version 3.28.1  the MD5 of the attributes is also checked and an exception is raised cause they definetely don't match.

see https://github.com/aws/aws-sdk-php/issues/1315

Many many thanks in advance and thank you for giving us such great tool to work in dev

**Comment by ingluisjimenez** [comment]
+1 on this.

Localstack is sending back the MD5OfMessageAttributes parameter, even when the client doesn't send any attributes with the message, and the hash is the md5 hash for an empty string "d41d8cd98f00b204e9800998ecf8427e".

@luismontreal this is funny we are running through the same exact issue at the same time.

**Comment by kstich** [comment]
The field `MD5OfMessageAttributes` does not exist on a `Message` if no attributes were set. 
<img width="620" alt="md5ofmessageattributes" src="https://user-images.githubusercontent.com/26905335/27655424-323dd918-5bfa-11e7-8812-2044e3e4e145.png">

**Comment by ingluisjimenez** [comment]
I assume this issue belongs on moto, which is the python library that localstack uses for SQS.

I see the support for MD5 calculation of SQS message attributes was added two months ago to that library, so definitely  it's something new. I can see in the code where it would return the hash for an empty string when there are no message attributes.

https://github.com/spulec/moto/commit/5e88b5d1b49bc853f67969b2b7cc0b9bc346d9f9

I think we should move this issue to that repo as well.

**Comment by ingluisjimenez** [comment]
I added this issue https://github.com/spulec/moto/issues/993 and opened a PR with the proposed fix https://github.com/spulec/moto/pull/992.

It's interesting that the previous logic was working the desired way, to only include the `MD5OfMessageAttributes` param when there is at least 1 message attribute, but it was reverted 2 months ago. Wondering if the aws-sdk for java/ruby are also having the same issue, or if the issue only affecting the php sdk.

**Comment by JackDanger** [comment]
Thanks to @ingluisjimenez this is now fixed in Moto

**Comment by ingluisjimenez** [comment]
Hey @whummer, this is fixed now in upstream, but there is no scheduled release for moto yet. Is there any chance to switch localstack to use the head from master for the moto requirement?

**Comment by ingluisjimenez** [comment]
@whummer you are the best!! 🙌

**Comment by ingluisjimenez** [comment]
@whummer tried to get the latest from localstack, but seems like it's not picking the latest from moto.

I see the `moto_ext-1.0.1.2.dist-info` folder in site-packages, as well the the responses.py inside the sqs module, which contains the fix, doesn't have it.Maybe I'm not getting the latest localstack? I made sure to remove the image and pull the 0.5.5 tag manually, but no luck.

**Comment by bgetsug** [comment]
I'm also still experiencing this issue with the latest localstack Docker image:
```
╰─➤  docker images | grep localstack                                                                                                                                                                                                                                                                                                                       129 ↵
atlassianlabs/localstack                           latest                       baa2e936b830        8 hours ago         1.19GB
```
```
 [Aws\Sqs\Exception\SqsException]                                                        
  Attribute MD5 mismatch. Expected d41d8cd98f00b204e9800998ecf8427e, found No Attributes 
```

**Comment by whummer** [comment]
@ingluisjimenez @bgetsug Good catch, that was a oversight. The image had been built with the old `moto-ext` version `1.0.1.2` when instead it should have been `1.0.1.3`. This is now (hopefully) fixed, the image is being built here: https://bitbucket.org/atlassian/localstack/addon/pipelines/home#!/results/%7B6f1ec391-6d0c-47a7-b461-1ff6b70a2edc%7D Thanks
